name: EAS staging
run-name: EAS staging | ${{ github.run_id }} | branch - ${{ github.ref_name }}

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  eas-staging:
    if: startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret"
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Setup Secrets
        run: |
          echo "EXPO_PUBLIC_API_KEY=${{ secrets.EXPO_PUBLIC_API_KEY }}" >> .env
          echo "EXPO_PUBLIC_API_URL=${{ secrets.EXPO_PUBLIC_API_URL }}" >> .env
          echo "EXPO_PUBLIC_APP_NAME=${{ secrets.EXPO_PUBLIC_APP_NAME }}" >> .env

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: |
          npm install -g expo-cli
          npm install

      - name: Create staging preview
        uses: expo/expo-github-action/preview@v8
        with:
          command: eas update --branch staging --message "EAS staging preview from ${{ github.actor }} | branch - ${{ github.ref_name }}"
